### ISSUE TITLE
Job must not be accessed before initialization

### ISSUE THREAD

**Issue by haithamRD** [iamfarhad/LaravelRabbitMQ#5]
hey i got this exception in my worker log if anyone have got this issue 

{
  "exception": "[object] (Error(code: 0): Typed property iamfarhad\\LaravelRabbitMQ\\RabbitQueue::$rabbitMQJob must not be accessed before initialization at /var/www/app/vendor/iamfarhad/laravel-rabbitmq/src/RabbitQueue.php:188)
[stacktrace]
#0 /var/www/app/vendor/iamfarhad/laravel-rabbitmq/src/Connectors/RabbitMQConnector.php(47): iamfarhad\\LaravelRabbitMQ\\RabbitQueue->close()
#1 /var/www/app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(458): iamfarhad\\LaravelRabbitMQ\\Connectors\\RabbitMQConnector->iamfarhad\\LaravelRabbitMQ\\Connectors\\{closure}(Object(Illuminate\\Queue\\Events\\WorkerStopping))
#2 /var/www/app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Queu...', Array)
#3 /var/www/app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners('Illuminate\\\\Queu...', Array, false)
#4 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(754): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Queu...')
#5 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(197): Illuminate\\Queue\\Worker->stop(0, Object(Illuminate\\Queue\\WorkerOptions))
#6 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(137): Illuminate\\Queue\\Worker->daemon('rabbitmq', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#7 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(120): Illuminate\\Queue\\Console\\WorkCommand->runWorker('rabbitmq', 'default')
#8 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#9 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#11 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 /var/www/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call(Array)
#14 /var/www/app/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /var/www/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 /var/www/app/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /var/www/app/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /var/www/app/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/www/app/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 {main}
"
}

**Comment by SamjiDiamond** [comment]
Same here

**Comment by iamfarhad** [comment]
it will fix on next release

**Comment by iamfarhad** [comment]
fixed
